### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by deepdil-sp** [nvh95/react-linkedin-login-oauth2#13]
.btn-linkedin {
^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

**Comment by nvh95** [comment]
@deepdil-sp Thanks for your feedback. Can you provide a little more information like steps to reproduce this issue?

**Comment by deepdil-sp** [comment]
its a server side rendering, so when i use igot this error.

**Comment by baesse** [comment]
Same issue here, i'm using  next.js  and getting this error during the build

**Comment by marieqg** [comment]
Same issue here using next.js . Does any one have a way to fix it? Thanks in advance !

**Comment by nvh95** [comment]
This issue just got fixed in `1.0.9-alpha.0`. Please help to reinstall by running
```sh
npm i react-linkedin-login-oauth2@alpha
```
or 
```sh
yarn add react-linkedin-login-oauth2@alpha
```
The `1.0.9` will come in a few days. Thanks

**Comment by nvh95** [comment]
@all-contributors please add @deepdil-sp for bug

**Comment by quangphat** [comment]
I got a same issue, I installed 1.0.9-alpha.0 but still not working

**Comment by shivika24** [comment]
I got a same issue with the latest version.

**Comment by nvh95** [comment]
Please give it a try by running:
```
npm i react-linkedin-login-oauth2@alpha
```

See the usage at https://github.com/nvh95/react-linkedin-login-oauth2/blob/a16b68c642cdfea8fd8da102628b69825e03cef2/README.md#L44-L76

Please let me know if the problem is still persist. Thanks.

**Comment by nvh95** [comment]
I believe this issue is resolved in `2.0.0`. Please let me know if it persists
